name: Gerador Temporário de Keystore

on:
  workflow_dispatch: # Permite rodar manualmente clicando no botão

jobs:
  generate-keystore:
    runs-on: ubuntu-latest
    steps:
      - name: ☕ Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 🔑 Gerar Arquivo Keystore (.jks)
        run: |
          keytool -genkey -v \
            -keystore vltv-keystore.jks \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -alias key0 \
            -storepass vltv123456 \
            -keypass vltv123456 \
            -dname "CN=VLTV Plus, OU=App, O=VLTV, L=Belo Horizonte, ST=Minas Gerais, C=BR"

      - name: 📜 Converter para Base64 e Mostrar na Tela
        run: |
          echo "=================================================="
          echo "COPIE O CÓDIGO ABAIXO PARA O SECRET KEYSTORE_BASE64"
          echo "=================================================="
          base64 -w 0 vltv-keystore.jks
          echo ""
          echo ""
          echo "=================================================="

      - name: 💾 Salvar Arquivo Keystore (Backup)
        uses: actions/upload-artifact@v4
        with:
          name: vltv-keystore-backup
          path: vltv-keystore.jks
          retention-days: 5
